data_sets: 
    tweets: 
        fname: 'annotated_german_refugee_tweets.csv'
        text_col: 'text'
        label_cols: 
            - 'annotation'
        language: 'de'
        y_col: 'annotation'
        n_jobs: 4
        n_cap: null
    wikipedia_hate_speech:
        fname: 'wikipedia_hate_speech.csv'
        text_col: 'comment_text'
        label_cols: 
            - 'toxic' 
            - 'severe_toxic'
            - 'obscene'
            - 'threat'
            - 'insult'
            - 'identity_hate'
        language: 'en'
        y_col: 'toxic'
        n_jobs: 4
        n_cap: 25000
    breitbart:
        fname: 'breitbart_data.csv'
        text_col: 'text'
        label_cols: 
            - 'muslim_identity' 
        language: 'en'
        y_col: 'muslim_identity'
        n_jobs: 4
        n_cap: null
text_features:
    tfidf: [on, off]
    stem: [on, off]
    token_type: 
        - ['word', 1] 
        - ['word', 2]
        - ['char_wb', 3]
        - ['char_wb', 4]
        - ['char_wb', 5]
