data_sets: 
    tweets: 
        fname: 'annotated_german_refugee_tweets.csv'
        text_col: 'text'
        language: 'de'
        n_records: 24420
        y_col: 'annotation'
    wikipedia_hate_speech:
        fname: 'wikipedia_hate_speech.csv'
        text_col: 'comment_text'
        language: 'en'
        n_records: 159571
        y_col: 'toxic'
text_features:
    tfidf: [on, off]
    stem: [on, off]
    token_type: 
        - ['word', 1] 
        - ['word', 2]
        - ['char_wb', 3]
        - ['char_wb', 4]
        - ['char_wb', 5]
